Q1

In [32]:
import numpy as np
arr1 = np.arange(1, 13)
arr1 = arr1.reshape(3, 4)
print("数组维度:", arr1.ndim)
print("数组形状:", arr1.shape)
print("数组元素总个数:", arr1.size)

数组维度: 2
数组形状: (3, 4)
数组元素总个数: 12


Q2

In [33]:
import numpy as np
arr2 = np.array([1.5, 2.6, 3.7, 4.8])
print("转换前数组:", arr2)
print("转换前数据类型:", arr2.dtype.name)

arr2_int32 = arr2.astype(np.int32)
print("\n转换后数组:", arr2_int32)
print("转换后数据类型:", arr2_int32.dtype.name)

转换前数组: [1.5 2.6 3.7 4.8]
转换前数据类型: float64

转换后数组: [1 2 3 4]
转换后数据类型: int32


Q3

In [34]:
import numpy as np
arr3 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
sub_arr = arr3[:2, 1:3]
print("原数组:")
print(arr3)
print("\n切片后的子数组:")
print(sub_arr)

原数组:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

切片后的子数组:
[[2 3]
 [6 7]]


Q4

In [35]:
import numpy as np
arr = np.array([10, 15, 20, 25, 30, 35])
r1 = arr[[0, 2, 4]]
print("花式索引结果:", r1)
r2 = arr[arr > 20]
print("布尔索引结果:", r2)

花式索引结果: [10 20 30]
布尔索引结果: [25 30 35]


Q5

In [36]:
import numpy as np
arr_a = np.zeros((3, 4))
arr_b = np.array([1, 2, 3, 4])
r = arr_a + arr_b
print("广播相加结果:")
print(r)

广播相加结果:
[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


Q6

In [37]:
import numpy as np
x = np.array([1, 4, 9, 16])
y = np.array([2, 1, 4, 5])
sqrt_x = np.sqrt(x)
print("x的平方根:", sqrt_x)
max = np.maximum(sqrt_x, y)
print("对应位置最大值:", max)

x的平方根: [1. 2. 3. 4.]
对应位置最大值: [2. 2. 4. 5.]


Q7

In [38]:
import numpy as np
arr = np.arange(24).reshape((2, 3, 4))
transposed_arr = arr.transpose((1, 0, 2))
print("转换后数组的形状:", transposed_arr.shape)

转换后数组的形状: (3, 2, 4)


Q8

In [39]:
import numpy as np
arr_x = np.array([1, 5, 7])
arr_y = np.array([2, 6, 8])
arr_con = np.array([True, False, True])
r = np.where(arr_con, arr_x, arr_y)
print("条件逻辑运算结果:", r)

条件逻辑运算结果: [1 6 7]


Q9

In [43]:
import numpy as np
arr = np.array([[6, 2, 7], [3, 6, 2], [4, 3, 2]])
m = arr.mean()
print("数组所有元素的算术平均值:", m)
arr.sort(axis=0)
print("按列排序后的数组:")
print(arr)
arr.mean(axis=1)

数组所有元素的算术平均值: 3.888888888888889
按列排序后的数组:
[[3 2 2]
 [4 3 2]
 [6 6 7]]


array([2.33333333, 3.        , 6.33333333])

Q10

In [41]:
import numpy as np
np.random.seed(10)
A = np.random.rand(2, 2)
B = np.random.rand(2, 2)
print("矩阵A:")
print(A)
print("\n矩阵B:")
print(B)
dot_product = np.dot(A, B)
print("\n矩阵A和B的点积结果:")
print(dot_product)

矩阵A:
[[0.77132064 0.02075195]
 [0.63364823 0.74880388]]

矩阵B:
[[0.49850701 0.22479665]
 [0.19806286 0.76053071]]

矩阵A和B的点积结果:
[[0.38861894 0.18917279]
 [0.46418833 0.71193035]]
